# Generated by Django 3.0.3 on 2020-02-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='additional_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='additional_text',
            field=models.TextField(blank=True),
        ),
    ]
