# Generated by Django 3.0.3 on 2020-03-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200302_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='additional_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='additional_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reapeted',
        ),
    ]
